CREATE TABLE DEPT (
    DEPTID INT AUTO_INCREMENT PRIMARY KEY,
    DEPTNAME VARCHAR(100) NOT NULL
);

CREATE TABLE USERS (
    USERID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    DEPTID INT,
    POSITION VARCHAR(50),
    STATUS VARCHAR(20),
    JOINED DATE,
    RESIGNED DATE,
    PROFILE_IMAGE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_USERS_DEPT FOREIGN KEY (DEPTID) REFERENCES DEPT(DEPTID) ON DELETE SET NULL
);

CREATE TABLE USERROLE (
    ROLEID INT AUTO_INCREMENT PRIMARY KEY,
    ROLENAME VARCHAR(50) NOT NULL,
    USERID BIGINT,
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

CREATE TABLE USERTODO (
    TODOID INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(500) NOT NULL,
    COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
    USERID BIGINT NOT NULL,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

CREATE TABLE USERSCHEDULE (
    SCHEDULEID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    STARTDATE TIMESTAMP,
    ENDDATE TIMESTAMP,
    USERID BIGINT NOT NULL,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

CREATE TABLE USEREMAIL (
	EMAILID INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(1000) NOT NULL,
    SENDER BIGINT NOT NULL,
    RECEIVER BIGINT NOT NULL,
    IS_READ BOOLEAN DEFAULT FALSE,
    SENT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER) REFERENCES USERS(USERID),
    FOREIGN KEY (RECEIVER) REFERENCES USERS(USERID)
);

CREATE TABLE BOARD (
    BOARDID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP,  
    WRITER VARCHAR(50) NOT NULL,                    
    ISNOTICE BOOLEAN DEFAULT FALSE,                
    PRIMARY KEY (BOARDID)
);

CREATE TABLE BOARD_ATTACHMENT (
    ATTACHMENT_ID INT NOT NULL AUTO_INCREMENT,
    BOARDID INT NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,        
    FILE_PATH VARCHAR(500) NOT NULL,        
    FILE_SIZE BIGINT,                       
    UPLOAD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ATTACHMENT_ID),
    FOREIGN KEY (BOARDID) REFERENCES BOARD(BOARDID) ON DELETE CASCADE
);

CREATE TABLE SCHEDULE (
    SCHEDULEID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    STARTDATE TIMESTAMP,
    ENDDATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
